// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchUIClient is the client API for SearchUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchUIClient interface {
	// ListEngineSpecs returns a list of Search Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SearchUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type searchUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchUIClient(cc grpc.ClientConnInterface) SearchUIClient {
	return &searchUIClient{cc}
}

func (c *searchUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SearchUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SearchUI_ServiceDesc.Streams[0], "/v1.SearchUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SearchUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type searchUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *searchUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *searchUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SearchUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchUIServer is the server API for SearchUI service.
// All implementations must embed UnimplementedSearchUIServer
// for forward compatibility
type SearchUIServer interface {
	// ListEngineSpecs returns a list of Search Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, SearchUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSearchUIServer()
}

// UnimplementedSearchUIServer must be embedded to have forward compatible implementations.
type UnimplementedSearchUIServer struct {
}

func (UnimplementedSearchUIServer) ListEngineSpecs(*ListEngineSpecsRequest, SearchUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedSearchUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSearchUIServer) mustEmbedUnimplementedSearchUIServer() {}

// UnsafeSearchUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchUIServer will
// result in compilation errors.
type UnsafeSearchUIServer interface {
	mustEmbedUnimplementedSearchUIServer()
}

func RegisterSearchUIServer(s grpc.ServiceRegistrar, srv SearchUIServer) {
	s.RegisterService(&SearchUI_ServiceDesc, srv)
}

func _SearchUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SearchUIServer).ListEngineSpecs(m, &searchUIListEngineSpecsServer{stream})
}

type SearchUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type searchUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *searchUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SearchUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SearchUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchUI_ServiceDesc is the grpc.ServiceDesc for SearchUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SearchUI",
	HandlerType: (*SearchUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SearchUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _SearchUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "search-ui.proto",
}
